-- Ligue 1 Express V8.4 — Analytics internes
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id text not null,
  session_id text not null,
  path text not null,
  referrer text not null default 'direct',
  device text not null default 'unknown' check (device in ('mobile','tablet','desktop','unknown'))
);

create index if not exists page_views_created_at_idx on public.page_views (created_at desc);
create index if not exists page_views_path_idx on public.page_views (path);
create index if not exists page_views_visitor_idx on public.page_views (visitor_id);

alter table public.page_views enable row level security;

drop policy if exists "Public can record page views" on public.page_views;
create policy "Public can record page views"
on public.page_views for insert
to anon, authenticated
with check (
  char_length(path) between 1 and 500
  and path not like '/admin%'
  and char_length(visitor_id) between 8 and 100
  and char_length(session_id) between 8 and 100
);

drop policy if exists "Authenticated can read analytics" on public.page_views;
create policy "Authenticated can read analytics"
on public.page_views for select
to authenticated
using (true);

create or replace function public.analytics_summary(p_days integer default 30)
returns jsonb
language sql
security invoker
set search_path = public
as $$
with params as (
  select greatest(1, least(coalesce(p_days, 30), 365))::integer as days
), period_rows as (
  select pv.*
  from public.page_views pv, params p
  where pv.created_at >= date_trunc('day', now()) - ((p.days - 1) * interval '1 day')
), today_rows as (
  select * from public.page_views where created_at >= date_trunc('day', now())
), dates as (
  select generate_series(
    date_trunc('day', now()) - (((select days from params) - 1) * interval '1 day'),
    date_trunc('day', now()),
    interval '1 day'
  )::date as day
), daily as (
  select d.day,
         count(p.id)::bigint as visits,
         count(distinct p.visitor_id)::bigint as visitors
  from dates d
  left join period_rows p on p.created_at::date = d.day
  group by d.day
  order by d.day
), top_pages as (
  select path, count(*)::bigint as visits, count(distinct visitor_id)::bigint as visitors
  from period_rows
  group by path
  order by visits desc, visitors desc, path
  limit 10
), devices as (
  select device, count(*)::bigint as visits
  from period_rows
  group by device
  order by visits desc
), sources as (
  select referrer, count(*)::bigint as visits
  from period_rows
  where referrer <> 'internal'
  group by referrer
  order by visits desc
  limit 10
)
select jsonb_build_object(
  'today_visits', (select count(*) from today_rows),
  'today_visitors', (select count(distinct visitor_id) from today_rows),
  'period_visits', (select count(*) from period_rows),
  'period_visitors', (select count(distinct visitor_id) from period_rows),
  'daily', coalesce((select jsonb_agg(jsonb_build_object('day', day, 'visits', visits, 'visitors', visitors) order by day) from daily), '[]'::jsonb),
  'top_pages', coalesce((select jsonb_agg(jsonb_build_object('path', path, 'visits', visits, 'visitors', visitors)) from top_pages), '[]'::jsonb),
  'devices', coalesce((select jsonb_agg(jsonb_build_object('device', device, 'visits', visits)) from devices), '[]'::jsonb),
  'sources', coalesce((select jsonb_agg(jsonb_build_object('referrer', referrer, 'visits', visits)) from sources), '[]'::jsonb)
);
$$;

revoke execute on function public.analytics_summary(integer) from public, anon;
grant execute on function public.analytics_summary(integer) to authenticated;
