import Link from "next/link";
import { getFrenchEuropeanMatches } from "@/lib/europe-france";

export const dynamic = "force-dynamic";
export const metadata = { title: "Coupes d'Europe — Clubs français", description: "Ligue des champions, Europa League et Conference League : le parcours des clubs français." };

function dateLabel(match){if(!match.utcDate)return "Date à confirmer";return new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(new Date(match.utcDate));}
function Match({match}){const finished=match.status==="FINISHED";const live=match.matchLive||["LIVE","PAUSED"].includes(match.status);return <Link href={`/live/match/${match.id}`} className="championship-card"><div className="championship-card-badge">{live?"🔴":finished?"FT":"🇪🇺"}</div><div><span>{dateLabel(match)} · {match.round||match.leagueName}</span><h2>{match.home.name} {finished||live?`${match.score?.home??"-"} - ${match.score?.away??"-"}`:"vs"} {match.away.name}</h2><p>{live?"Match en direct — ouvrir le Centre Match":finished?"Résultat — résumé et informations du match":"Prochain match — informations et Centre Match"}</p></div><b>→</b></Link>}

export default async function EuropePage(){const result=await getFrenchEuropeanMatches();const matches=result.ok?result.data:[];const now=Math.floor(Date.now()/1000);const groups=(result.competitions||[]).map(c=>{const all=matches.filter(m=>m.league?.slug===c.slug);return{...c,all,recent:all.filter(m=>m.status==="FINISHED").sort((a,b)=>b.timestamp-a.timestamp),upcoming:all.filter(m=>m.status!=="FINISHED"&&m.timestamp>=now-10800).sort((a,b)=>a.timestamp-b.timestamp)};});return <div className="page-shell listing-page championships-index"><span className="eyebrow">🇪🇺 CLUBS FRANÇAIS EN EUROPE</span><h1>Coupes d'Europe</h1><p className="championships-intro">Toute la campagne européenne des clubs français : Ligue des champions, Europa League et Conference League. Les rencontres sans club français sont volontairement exclues.</p>{!result.ok&&<div className="live-v83-source-note">Données européennes momentanément indisponibles : {result.error}</div>}{groups.map(g=><section key={g.slug} style={{marginTop:"2rem"}}><div className="live-v83-section-head"><h2>{g.name}</h2><span>{g.all.length} match{g.all.length>1?"s":""} français</span></div>{g.upcoming.length>0&&<><h3>Prochains matchs</h3><div className="championship-card-grid">{g.upcoming.slice(0,12).map(m=><Match key={m.id} match={m}/>)}</div></>}{g.recent.length>0&&<><h3 style={{marginTop:"1.5rem"}}>Derniers résultats</h3><div className="championship-card-grid">{g.recent.slice(0,12).map(m=><Match key={m.id} match={m}/>)}</div></>}{!g.all.length&&<p>Aucun match d'un club français disponible actuellement dans cette compétition.</p>}</section>)}</div>}
